// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MonitorAlarmsService.proto

package smartair.monitorAlarmsService;

public interface alertMonitorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartair.monitorAlarmsService.alertMonitorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool alertMessage = 1;</code>
   */
  boolean getAlertMessage();
}
