// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MonitorAlarmsService.proto

package smartair.monitorAlarmsService;

/**
 * Protobuf type {@code smartair.monitorAlarmsService.alertMonitorResponse}
 */
public  final class alertMonitorResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:smartair.monitorAlarmsService.alertMonitorResponse)
    alertMonitorResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use alertMonitorResponse.newBuilder() to construct.
  private alertMonitorResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private alertMonitorResponse() {
    alertMessage_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private alertMonitorResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            alertMessage_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return smartair.monitorAlarmsService.monitorAlarmsServiceImpl.internal_static_smartair_monitorAlarmsService_alertMonitorResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return smartair.monitorAlarmsService.monitorAlarmsServiceImpl.internal_static_smartair_monitorAlarmsService_alertMonitorResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            smartair.monitorAlarmsService.alertMonitorResponse.class, smartair.monitorAlarmsService.alertMonitorResponse.Builder.class);
  }

  public static final int ALERTMESSAGE_FIELD_NUMBER = 1;
  private boolean alertMessage_;
  /**
   * <code>bool alertMessage = 1;</code>
   */
  public boolean getAlertMessage() {
    return alertMessage_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (alertMessage_ != false) {
      output.writeBool(1, alertMessage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (alertMessage_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, alertMessage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof smartair.monitorAlarmsService.alertMonitorResponse)) {
      return super.equals(obj);
    }
    smartair.monitorAlarmsService.alertMonitorResponse other = (smartair.monitorAlarmsService.alertMonitorResponse) obj;

    boolean result = true;
    result = result && (getAlertMessage()
        == other.getAlertMessage());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ALERTMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAlertMessage());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static smartair.monitorAlarmsService.alertMonitorResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smartair.monitorAlarmsService.alertMonitorResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smartair.monitorAlarmsService.alertMonitorResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smartair.monitorAlarmsService.alertMonitorResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smartair.monitorAlarmsService.alertMonitorResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smartair.monitorAlarmsService.alertMonitorResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smartair.monitorAlarmsService.alertMonitorResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static smartair.monitorAlarmsService.alertMonitorResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static smartair.monitorAlarmsService.alertMonitorResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static smartair.monitorAlarmsService.alertMonitorResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static smartair.monitorAlarmsService.alertMonitorResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static smartair.monitorAlarmsService.alertMonitorResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(smartair.monitorAlarmsService.alertMonitorResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code smartair.monitorAlarmsService.alertMonitorResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:smartair.monitorAlarmsService.alertMonitorResponse)
      smartair.monitorAlarmsService.alertMonitorResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smartair.monitorAlarmsService.monitorAlarmsServiceImpl.internal_static_smartair_monitorAlarmsService_alertMonitorResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smartair.monitorAlarmsService.monitorAlarmsServiceImpl.internal_static_smartair_monitorAlarmsService_alertMonitorResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smartair.monitorAlarmsService.alertMonitorResponse.class, smartair.monitorAlarmsService.alertMonitorResponse.Builder.class);
    }

    // Construct using smartair.monitorAlarmsService.alertMonitorResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      alertMessage_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return smartair.monitorAlarmsService.monitorAlarmsServiceImpl.internal_static_smartair_monitorAlarmsService_alertMonitorResponse_descriptor;
    }

    @java.lang.Override
    public smartair.monitorAlarmsService.alertMonitorResponse getDefaultInstanceForType() {
      return smartair.monitorAlarmsService.alertMonitorResponse.getDefaultInstance();
    }

    @java.lang.Override
    public smartair.monitorAlarmsService.alertMonitorResponse build() {
      smartair.monitorAlarmsService.alertMonitorResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public smartair.monitorAlarmsService.alertMonitorResponse buildPartial() {
      smartair.monitorAlarmsService.alertMonitorResponse result = new smartair.monitorAlarmsService.alertMonitorResponse(this);
      result.alertMessage_ = alertMessage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof smartair.monitorAlarmsService.alertMonitorResponse) {
        return mergeFrom((smartair.monitorAlarmsService.alertMonitorResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(smartair.monitorAlarmsService.alertMonitorResponse other) {
      if (other == smartair.monitorAlarmsService.alertMonitorResponse.getDefaultInstance()) return this;
      if (other.getAlertMessage() != false) {
        setAlertMessage(other.getAlertMessage());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      smartair.monitorAlarmsService.alertMonitorResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (smartair.monitorAlarmsService.alertMonitorResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean alertMessage_ ;
    /**
     * <code>bool alertMessage = 1;</code>
     */
    public boolean getAlertMessage() {
      return alertMessage_;
    }
    /**
     * <code>bool alertMessage = 1;</code>
     */
    public Builder setAlertMessage(boolean value) {
      
      alertMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool alertMessage = 1;</code>
     */
    public Builder clearAlertMessage() {
      
      alertMessage_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:smartair.monitorAlarmsService.alertMonitorResponse)
  }

  // @@protoc_insertion_point(class_scope:smartair.monitorAlarmsService.alertMonitorResponse)
  private static final smartair.monitorAlarmsService.alertMonitorResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new smartair.monitorAlarmsService.alertMonitorResponse();
  }

  public static smartair.monitorAlarmsService.alertMonitorResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<alertMonitorResponse>
      PARSER = new com.google.protobuf.AbstractParser<alertMonitorResponse>() {
    @java.lang.Override
    public alertMonitorResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new alertMonitorResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<alertMonitorResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<alertMonitorResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public smartair.monitorAlarmsService.alertMonitorResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

