// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MonitorAlarmsService.proto

package smartair.monitorAlarmsService;

public interface setThresholdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartair.monitorAlarmsService.setThresholdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float threshold = 1;</code>
   */
  float getThreshold();
}
