// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MonitorAlarmsService.proto

package smartair.monitorAlarmsService;

/**
 * Protobuf type {@code smartair.monitorAlarmsService.setThresholdResponse}
 */
public  final class setThresholdResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:smartair.monitorAlarmsService.setThresholdResponse)
    setThresholdResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use setThresholdResponse.newBuilder() to construct.
  private setThresholdResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private setThresholdResponse() {
    thresholdSet_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private setThresholdResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            thresholdSet_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return smartair.monitorAlarmsService.monitorAlarmsServiceImpl.internal_static_smartair_monitorAlarmsService_setThresholdResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return smartair.monitorAlarmsService.monitorAlarmsServiceImpl.internal_static_smartair_monitorAlarmsService_setThresholdResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            smartair.monitorAlarmsService.setThresholdResponse.class, smartair.monitorAlarmsService.setThresholdResponse.Builder.class);
  }

  public static final int THRESHOLDSET_FIELD_NUMBER = 1;
  private boolean thresholdSet_;
  /**
   * <code>bool thresholdSet = 1;</code>
   */
  public boolean getThresholdSet() {
    return thresholdSet_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (thresholdSet_ != false) {
      output.writeBool(1, thresholdSet_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (thresholdSet_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, thresholdSet_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof smartair.monitorAlarmsService.setThresholdResponse)) {
      return super.equals(obj);
    }
    smartair.monitorAlarmsService.setThresholdResponse other = (smartair.monitorAlarmsService.setThresholdResponse) obj;

    boolean result = true;
    result = result && (getThresholdSet()
        == other.getThresholdSet());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + THRESHOLDSET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getThresholdSet());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static smartair.monitorAlarmsService.setThresholdResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smartair.monitorAlarmsService.setThresholdResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smartair.monitorAlarmsService.setThresholdResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smartair.monitorAlarmsService.setThresholdResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smartair.monitorAlarmsService.setThresholdResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smartair.monitorAlarmsService.setThresholdResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smartair.monitorAlarmsService.setThresholdResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static smartair.monitorAlarmsService.setThresholdResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static smartair.monitorAlarmsService.setThresholdResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static smartair.monitorAlarmsService.setThresholdResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static smartair.monitorAlarmsService.setThresholdResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static smartair.monitorAlarmsService.setThresholdResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(smartair.monitorAlarmsService.setThresholdResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code smartair.monitorAlarmsService.setThresholdResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:smartair.monitorAlarmsService.setThresholdResponse)
      smartair.monitorAlarmsService.setThresholdResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smartair.monitorAlarmsService.monitorAlarmsServiceImpl.internal_static_smartair_monitorAlarmsService_setThresholdResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smartair.monitorAlarmsService.monitorAlarmsServiceImpl.internal_static_smartair_monitorAlarmsService_setThresholdResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smartair.monitorAlarmsService.setThresholdResponse.class, smartair.monitorAlarmsService.setThresholdResponse.Builder.class);
    }

    // Construct using smartair.monitorAlarmsService.setThresholdResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      thresholdSet_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return smartair.monitorAlarmsService.monitorAlarmsServiceImpl.internal_static_smartair_monitorAlarmsService_setThresholdResponse_descriptor;
    }

    @java.lang.Override
    public smartair.monitorAlarmsService.setThresholdResponse getDefaultInstanceForType() {
      return smartair.monitorAlarmsService.setThresholdResponse.getDefaultInstance();
    }

    @java.lang.Override
    public smartair.monitorAlarmsService.setThresholdResponse build() {
      smartair.monitorAlarmsService.setThresholdResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public smartair.monitorAlarmsService.setThresholdResponse buildPartial() {
      smartair.monitorAlarmsService.setThresholdResponse result = new smartair.monitorAlarmsService.setThresholdResponse(this);
      result.thresholdSet_ = thresholdSet_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof smartair.monitorAlarmsService.setThresholdResponse) {
        return mergeFrom((smartair.monitorAlarmsService.setThresholdResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(smartair.monitorAlarmsService.setThresholdResponse other) {
      if (other == smartair.monitorAlarmsService.setThresholdResponse.getDefaultInstance()) return this;
      if (other.getThresholdSet() != false) {
        setThresholdSet(other.getThresholdSet());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      smartair.monitorAlarmsService.setThresholdResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (smartair.monitorAlarmsService.setThresholdResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean thresholdSet_ ;
    /**
     * <code>bool thresholdSet = 1;</code>
     */
    public boolean getThresholdSet() {
      return thresholdSet_;
    }
    /**
     * <code>bool thresholdSet = 1;</code>
     */
    public Builder setThresholdSet(boolean value) {
      
      thresholdSet_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool thresholdSet = 1;</code>
     */
    public Builder clearThresholdSet() {
      
      thresholdSet_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:smartair.monitorAlarmsService.setThresholdResponse)
  }

  // @@protoc_insertion_point(class_scope:smartair.monitorAlarmsService.setThresholdResponse)
  private static final smartair.monitorAlarmsService.setThresholdResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new smartair.monitorAlarmsService.setThresholdResponse();
  }

  public static smartair.monitorAlarmsService.setThresholdResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<setThresholdResponse>
      PARSER = new com.google.protobuf.AbstractParser<setThresholdResponse>() {
    @java.lang.Override
    public setThresholdResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new setThresholdResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<setThresholdResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<setThresholdResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public smartair.monitorAlarmsService.setThresholdResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

