// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MonitorAlarmsService.proto

package smartair.monitorAlarmsService;

public interface setThresholdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartair.monitorAlarmsService.setThresholdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool thresholdSet = 1;</code>
   */
  boolean getThresholdSet();
}
