// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SensorService.proto

package smartair.sensorService;

public interface getDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartair.sensorService.getDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *time of data detection
   * </pre>
   *
   * <code>double timeStamp = 1;</code>
   */
  double getTimeStamp();
}
