// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SensorService.proto

package smartair.sensorService;

public interface inputDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartair.sensorService.inputDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool dataRegistred = 1;</code>
   */
  boolean getDataRegistred();
}
