// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SensorService.proto

package smartair.sensorService;

public interface inputDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartair.sensorService.inputDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *current timestamp of data
   * </pre>
   *
   * <code>double currentTimeStamp = 1;</code>
   */
  double getCurrentTimeStamp();

  /**
   * <pre>
   *COemission detected
   * </pre>
   *
   * <code>float coReading = 2;</code>
   */
  float getCoReading();
}
