// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataAnalisysService.proto

package smartair.dataAnalisysService;

/**
 * Protobuf type {@code smartair.dataAnalisysService.getDataResponse}
 */
public  final class getDataResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:smartair.dataAnalisysService.getDataResponse)
    getDataResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use getDataResponse.newBuilder() to construct.
  private getDataResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private getDataResponse() {
    fromTimeStamp_ = 0D;
    currentTimeStamp_ = 0D;
    coReading_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private getDataResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            fromTimeStamp_ = input.readDouble();
            break;
          }
          case 17: {

            currentTimeStamp_ = input.readDouble();
            break;
          }
          case 29: {

            coReading_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return smartair.dataAnalisysService.dataAnalisysServiceImpl.internal_static_smartair_dataAnalisysService_getDataResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return smartair.dataAnalisysService.dataAnalisysServiceImpl.internal_static_smartair_dataAnalisysService_getDataResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            smartair.dataAnalisysService.getDataResponse.class, smartair.dataAnalisysService.getDataResponse.Builder.class);
  }

  public static final int FROMTIMESTAMP_FIELD_NUMBER = 1;
  private double fromTimeStamp_;
  /**
   * <pre>
   *last timestamp of data 
   * </pre>
   *
   * <code>double fromTimeStamp = 1;</code>
   */
  public double getFromTimeStamp() {
    return fromTimeStamp_;
  }

  public static final int CURRENTTIMESTAMP_FIELD_NUMBER = 2;
  private double currentTimeStamp_;
  /**
   * <pre>
   *current timestamp of data
   * </pre>
   *
   * <code>double currentTimeStamp = 2;</code>
   */
  public double getCurrentTimeStamp() {
    return currentTimeStamp_;
  }

  public static final int COREADING_FIELD_NUMBER = 3;
  private float coReading_;
  /**
   * <pre>
   *COemission detected
   * </pre>
   *
   * <code>float coReading = 3;</code>
   */
  public float getCoReading() {
    return coReading_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (fromTimeStamp_ != 0D) {
      output.writeDouble(1, fromTimeStamp_);
    }
    if (currentTimeStamp_ != 0D) {
      output.writeDouble(2, currentTimeStamp_);
    }
    if (coReading_ != 0F) {
      output.writeFloat(3, coReading_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (fromTimeStamp_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, fromTimeStamp_);
    }
    if (currentTimeStamp_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, currentTimeStamp_);
    }
    if (coReading_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, coReading_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof smartair.dataAnalisysService.getDataResponse)) {
      return super.equals(obj);
    }
    smartair.dataAnalisysService.getDataResponse other = (smartair.dataAnalisysService.getDataResponse) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getFromTimeStamp())
        == java.lang.Double.doubleToLongBits(
            other.getFromTimeStamp()));
    result = result && (
        java.lang.Double.doubleToLongBits(getCurrentTimeStamp())
        == java.lang.Double.doubleToLongBits(
            other.getCurrentTimeStamp()));
    result = result && (
        java.lang.Float.floatToIntBits(getCoReading())
        == java.lang.Float.floatToIntBits(
            other.getCoReading()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FROMTIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getFromTimeStamp()));
    hash = (37 * hash) + CURRENTTIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCurrentTimeStamp()));
    hash = (37 * hash) + COREADING_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getCoReading());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static smartair.dataAnalisysService.getDataResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smartair.dataAnalisysService.getDataResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smartair.dataAnalisysService.getDataResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smartair.dataAnalisysService.getDataResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smartair.dataAnalisysService.getDataResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smartair.dataAnalisysService.getDataResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smartair.dataAnalisysService.getDataResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static smartair.dataAnalisysService.getDataResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static smartair.dataAnalisysService.getDataResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static smartair.dataAnalisysService.getDataResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static smartair.dataAnalisysService.getDataResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static smartair.dataAnalisysService.getDataResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(smartair.dataAnalisysService.getDataResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code smartair.dataAnalisysService.getDataResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:smartair.dataAnalisysService.getDataResponse)
      smartair.dataAnalisysService.getDataResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smartair.dataAnalisysService.dataAnalisysServiceImpl.internal_static_smartair_dataAnalisysService_getDataResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smartair.dataAnalisysService.dataAnalisysServiceImpl.internal_static_smartair_dataAnalisysService_getDataResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smartair.dataAnalisysService.getDataResponse.class, smartair.dataAnalisysService.getDataResponse.Builder.class);
    }

    // Construct using smartair.dataAnalisysService.getDataResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      fromTimeStamp_ = 0D;

      currentTimeStamp_ = 0D;

      coReading_ = 0F;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return smartair.dataAnalisysService.dataAnalisysServiceImpl.internal_static_smartair_dataAnalisysService_getDataResponse_descriptor;
    }

    @java.lang.Override
    public smartair.dataAnalisysService.getDataResponse getDefaultInstanceForType() {
      return smartair.dataAnalisysService.getDataResponse.getDefaultInstance();
    }

    @java.lang.Override
    public smartair.dataAnalisysService.getDataResponse build() {
      smartair.dataAnalisysService.getDataResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public smartair.dataAnalisysService.getDataResponse buildPartial() {
      smartair.dataAnalisysService.getDataResponse result = new smartair.dataAnalisysService.getDataResponse(this);
      result.fromTimeStamp_ = fromTimeStamp_;
      result.currentTimeStamp_ = currentTimeStamp_;
      result.coReading_ = coReading_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof smartair.dataAnalisysService.getDataResponse) {
        return mergeFrom((smartair.dataAnalisysService.getDataResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(smartair.dataAnalisysService.getDataResponse other) {
      if (other == smartair.dataAnalisysService.getDataResponse.getDefaultInstance()) return this;
      if (other.getFromTimeStamp() != 0D) {
        setFromTimeStamp(other.getFromTimeStamp());
      }
      if (other.getCurrentTimeStamp() != 0D) {
        setCurrentTimeStamp(other.getCurrentTimeStamp());
      }
      if (other.getCoReading() != 0F) {
        setCoReading(other.getCoReading());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      smartair.dataAnalisysService.getDataResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (smartair.dataAnalisysService.getDataResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double fromTimeStamp_ ;
    /**
     * <pre>
     *last timestamp of data 
     * </pre>
     *
     * <code>double fromTimeStamp = 1;</code>
     */
    public double getFromTimeStamp() {
      return fromTimeStamp_;
    }
    /**
     * <pre>
     *last timestamp of data 
     * </pre>
     *
     * <code>double fromTimeStamp = 1;</code>
     */
    public Builder setFromTimeStamp(double value) {
      
      fromTimeStamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *last timestamp of data 
     * </pre>
     *
     * <code>double fromTimeStamp = 1;</code>
     */
    public Builder clearFromTimeStamp() {
      
      fromTimeStamp_ = 0D;
      onChanged();
      return this;
    }

    private double currentTimeStamp_ ;
    /**
     * <pre>
     *current timestamp of data
     * </pre>
     *
     * <code>double currentTimeStamp = 2;</code>
     */
    public double getCurrentTimeStamp() {
      return currentTimeStamp_;
    }
    /**
     * <pre>
     *current timestamp of data
     * </pre>
     *
     * <code>double currentTimeStamp = 2;</code>
     */
    public Builder setCurrentTimeStamp(double value) {
      
      currentTimeStamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *current timestamp of data
     * </pre>
     *
     * <code>double currentTimeStamp = 2;</code>
     */
    public Builder clearCurrentTimeStamp() {
      
      currentTimeStamp_ = 0D;
      onChanged();
      return this;
    }

    private float coReading_ ;
    /**
     * <pre>
     *COemission detected
     * </pre>
     *
     * <code>float coReading = 3;</code>
     */
    public float getCoReading() {
      return coReading_;
    }
    /**
     * <pre>
     *COemission detected
     * </pre>
     *
     * <code>float coReading = 3;</code>
     */
    public Builder setCoReading(float value) {
      
      coReading_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *COemission detected
     * </pre>
     *
     * <code>float coReading = 3;</code>
     */
    public Builder clearCoReading() {
      
      coReading_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:smartair.dataAnalisysService.getDataResponse)
  }

  // @@protoc_insertion_point(class_scope:smartair.dataAnalisysService.getDataResponse)
  private static final smartair.dataAnalisysService.getDataResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new smartair.dataAnalisysService.getDataResponse();
  }

  public static smartair.dataAnalisysService.getDataResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<getDataResponse>
      PARSER = new com.google.protobuf.AbstractParser<getDataResponse>() {
    @java.lang.Override
    public getDataResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new getDataResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<getDataResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<getDataResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public smartair.dataAnalisysService.getDataResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

