// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataAnalisysService.proto

package smartair.dataAnalisysService;

public interface getDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartair.dataAnalisysService.getDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *last timestamp of data 
   * </pre>
   *
   * <code>double fromTimeStamp = 1;</code>
   */
  double getFromTimeStamp();

  /**
   * <pre>
   *current timestamp of data
   * </pre>
   *
   * <code>double currentTimeStamp = 2;</code>
   */
  double getCurrentTimeStamp();

  /**
   * <pre>
   *COemission detected
   * </pre>
   *
   * <code>float coReading = 3;</code>
   */
  float getCoReading();
}
