// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataAnalisysService.proto

package smartair.dataAnalisysService;

/**
 * Protobuf type {@code smartair.dataAnalisysService.getDataRequest}
 */
public  final class getDataRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:smartair.dataAnalisysService.getDataRequest)
    getDataRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use getDataRequest.newBuilder() to construct.
  private getDataRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private getDataRequest() {
    timeStamp_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private getDataRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            timeStamp_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return smartair.dataAnalisysService.dataAnalisysServiceImpl.internal_static_smartair_dataAnalisysService_getDataRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return smartair.dataAnalisysService.dataAnalisysServiceImpl.internal_static_smartair_dataAnalisysService_getDataRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            smartair.dataAnalisysService.getDataRequest.class, smartair.dataAnalisysService.getDataRequest.Builder.class);
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 1;
  private double timeStamp_;
  /**
   * <pre>
   *time of data detection
   * </pre>
   *
   * <code>double timeStamp = 1;</code>
   */
  public double getTimeStamp() {
    return timeStamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timeStamp_ != 0D) {
      output.writeDouble(1, timeStamp_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timeStamp_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, timeStamp_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof smartair.dataAnalisysService.getDataRequest)) {
      return super.equals(obj);
    }
    smartair.dataAnalisysService.getDataRequest other = (smartair.dataAnalisysService.getDataRequest) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getTimeStamp())
        == java.lang.Double.doubleToLongBits(
            other.getTimeStamp()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTimeStamp()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static smartair.dataAnalisysService.getDataRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smartair.dataAnalisysService.getDataRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smartair.dataAnalisysService.getDataRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smartair.dataAnalisysService.getDataRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smartair.dataAnalisysService.getDataRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smartair.dataAnalisysService.getDataRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smartair.dataAnalisysService.getDataRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static smartair.dataAnalisysService.getDataRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static smartair.dataAnalisysService.getDataRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static smartair.dataAnalisysService.getDataRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static smartair.dataAnalisysService.getDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static smartair.dataAnalisysService.getDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(smartair.dataAnalisysService.getDataRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code smartair.dataAnalisysService.getDataRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:smartair.dataAnalisysService.getDataRequest)
      smartair.dataAnalisysService.getDataRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smartair.dataAnalisysService.dataAnalisysServiceImpl.internal_static_smartair_dataAnalisysService_getDataRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smartair.dataAnalisysService.dataAnalisysServiceImpl.internal_static_smartair_dataAnalisysService_getDataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smartair.dataAnalisysService.getDataRequest.class, smartair.dataAnalisysService.getDataRequest.Builder.class);
    }

    // Construct using smartair.dataAnalisysService.getDataRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      timeStamp_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return smartair.dataAnalisysService.dataAnalisysServiceImpl.internal_static_smartair_dataAnalisysService_getDataRequest_descriptor;
    }

    @java.lang.Override
    public smartair.dataAnalisysService.getDataRequest getDefaultInstanceForType() {
      return smartair.dataAnalisysService.getDataRequest.getDefaultInstance();
    }

    @java.lang.Override
    public smartair.dataAnalisysService.getDataRequest build() {
      smartair.dataAnalisysService.getDataRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public smartair.dataAnalisysService.getDataRequest buildPartial() {
      smartair.dataAnalisysService.getDataRequest result = new smartair.dataAnalisysService.getDataRequest(this);
      result.timeStamp_ = timeStamp_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof smartair.dataAnalisysService.getDataRequest) {
        return mergeFrom((smartair.dataAnalisysService.getDataRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(smartair.dataAnalisysService.getDataRequest other) {
      if (other == smartair.dataAnalisysService.getDataRequest.getDefaultInstance()) return this;
      if (other.getTimeStamp() != 0D) {
        setTimeStamp(other.getTimeStamp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      smartair.dataAnalisysService.getDataRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (smartair.dataAnalisysService.getDataRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double timeStamp_ ;
    /**
     * <pre>
     *time of data detection
     * </pre>
     *
     * <code>double timeStamp = 1;</code>
     */
    public double getTimeStamp() {
      return timeStamp_;
    }
    /**
     * <pre>
     *time of data detection
     * </pre>
     *
     * <code>double timeStamp = 1;</code>
     */
    public Builder setTimeStamp(double value) {
      
      timeStamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *time of data detection
     * </pre>
     *
     * <code>double timeStamp = 1;</code>
     */
    public Builder clearTimeStamp() {
      
      timeStamp_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:smartair.dataAnalisysService.getDataRequest)
  }

  // @@protoc_insertion_point(class_scope:smartair.dataAnalisysService.getDataRequest)
  private static final smartair.dataAnalisysService.getDataRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new smartair.dataAnalisysService.getDataRequest();
  }

  public static smartair.dataAnalisysService.getDataRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<getDataRequest>
      PARSER = new com.google.protobuf.AbstractParser<getDataRequest>() {
    @java.lang.Override
    public getDataRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new getDataRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<getDataRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<getDataRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public smartair.dataAnalisysService.getDataRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

